# Copyright 2020 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Params for FC MNIST model
description: "FC-MNIST base model params"

train_input:
    shuffle: True
    shuffle_buffer_size : 10000
    augment_data: True
    dataset_path: 'data' # Place to store data
    train_batch_size: 256
    eval_batch_size: 1024
    num_parallel_calls: 0   # 0 means AUTOTUNE
    # num_parallel_reads: 16
    train_test_split: 0.80
    num_classes: 6
    IR_threshould: 0.075
    patch_size: 96
    patch_step: 320
    dataset: "IR_dataset"
model:
    classes_num: 10
    hidden_size: 768
    heads_num: 12
    patch_size: 4
    mlp_dim: 3072
    encoders_num: 36
    dropout_rate: 0.1
    warmup_steps: 0
    decay_type: "linear"
    weight_decay: 0.0001
    tf_summary: False
    boundary_casting: False
    mixed_precision: True
    ret_scores: False
    layer_norm_epsilon: 1.0e-05
    ret_scores: False

optimizer:
    optimizer_type: 'adam' # {'sgd', 'momentum', 'adam', 'adamw'}
    weight_decay_rate: 0.01
    epsilon: 1e-6
    max_gradient_norm: 1.0
    disable_lr_steps_reset: True
    learning_rate:
        - steps: 10000
          scheduler: 'Linear'
          initial_learning_rate: 0.0
          end_learning_rate: 0.0001
        - scheduler: 'Linear'
          initial_learning_rate: 0.0001
          end_learning_rate: 0.0
          steps: 1000000
    loss_scaling_factor: 'dynamic'


runconfig:
    max_steps: 1000
    save_summary_steps: 500
    save_checkpoints_steps: 50
    keep_checkpoint_max: 2
    model_dir: 'model_dir'
    cs_ip:
    multireplica: False
    mode: 'train'
    eval_steps: 100