# Params for UNet model on Inria Aerial Dataset 5120 x 5120 images

train_input: &train_input
    data_processor: InriaAerialDataProcessor
    data_dir: "./computer_vision/datasets/AerialImageDataset_5120_5120" # ON CS
    image_shape: [5120, 5120, 1]  # [H, W, C]
    normalize_data_method: "zero_centered"
    augment_data: True
    shuffle: True
    shuffle_seed: 1234
    batch_size: 1
    num_classes: 2
    num_workers: 4
    prefetch_factor: 10
    persistent_workers: True

    use_fast_dataloader: False # Toggle to True for faster MAP style dataloader

eval_input: &eval_input
    <<: *train_input
    augment_data: False
    shuffle: False
    batch_size: 1
    num_workers: 2


model:
    nonlinearity: "ReLU"
    skip_connect: True
    enable_bias: True
    downscale_method: "max_pool"
    convs_per_block: ["3x3_conv", "3x3_conv"]
    encoder_filters: [32, 64, 128, 256, 512, 1024]
    decoder_filters: [512, 256, 128, 64, 32]
    residual_blocks: False
    initializer: 
        "name": "glorot_uniform"
        "gain": 1.0
    bias_initializer: "zeros"
    # bce -> Binary Cross Entropy With Logits
    loss: "bce"
    mixed_precision: True
    norm_layer: "group"
    norm_kwargs:
        num_groups: 16
    eval_metrics: ["Acc"]

optimizer:
    loss_scaling_factor: dynamic
    optimizer_type: AdamW
    correct_bias: True
    weight_decay_rate: 0.01
    disable_lr_steps_reset: True
    max_gradient_norm: 1.0
    learning_rate:
       - scheduler: "Linear"
         initial_learning_rate: 0.0
         end_learning_rate: 0.00025
         steps: 4000
       - scheduler: "Linear"
         initial_learning_rate: 0.00025
         end_learning_rate: 0.0
         steps: 10000

runconfig:
    max_steps: 10000
    log_steps: 1
    checkpoint_steps: 500
    seed: 1
    show_debug_metrics: False
    save_losses: True
    save_initial_checkpoint: True
    num_wgt_servers: 1
