#Model Params of UNet18 with severstal 5120x5120 image dataset

train_input: &train_input
  data_processor: Hdf5DataProcessor
  data_dir: "./computer_vision/datasets/severstal_hdf/severstal_binary_classid_3_hdf_5120x5120/train_input"
  image_shape: [5120, 5120, 1]  # [H, W, C]
  normalize_data_method: "zero_centered"
  augment_data: True
  shuffle: True
  batch_size: 1
  num_classes: 2
  num_workers: 8
  prefetch_factor: 10
  persistent_workers: True

eval_input:
  <<: *train_input
  data_dir: "./computer_vision/datasets/severstal_hdf/severstal_binary_classid_3_hdf_5120x5120/eval_input"
  augment_data: False
  shuffle: False
  batch_size: 1
  num_workers: 2

model:
  nonlinearity: "ReLU"
  skip_connect: True
  enable_bias: True
  downscale_method: "max_pool"  # Valid choices: {"strided_conv", "max_pool"}
  convs_per_block: ["3x3_conv", "3x3_conv"]
  encoder_filters: [32, 64, 128, 256]
  decoder_filters: [128, 64, 32]
  residual_blocks: False
  initializer: 
    "name": "glorot_uniform"
    "gain": 1.0
  bias_initializer: "zeros"
  # bce -> Binary Cross Entropy With Logits
  loss: "bce"
  mixed_precision: True

optimizer:
  optimizer_type: "AdamW"
  weight_decay_rate: 0.01
  learning_rate: 5.0e-4
  loss_scaling_factor: "dynamic"
  
runconfig:
  max_steps: 2000
  log_steps: 100
  checkpoint_steps: 500
  seed: 1
  show_debug_metrics: False
  save_losses: True
  save_initial_checkpoint: True
  num_wgt_servers: 1
