# GPT-3 XL model without sparse banded attention

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir:
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/0/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/1/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/2/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/3/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/4/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/5/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/6/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/7/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/8/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/9/"
    vocab_size: 50257
    max_sequence_length: 2048
    shuffle: False # for reproducibility
    batch_size: 121 # chosen for high utilization in weight streaming
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_msl2048/"
    vocab_size: 50257
    max_sequence_length: 2048
    batch_size: 121
    shuffle: False
    num_workers: 8

### Model
model:
    # Embedding
    hidden_size: 2048
    use_position_embedding: True
    position_embedding_type: "learned"
    share_embedding_weights: True
    # embedding_initializer: "uniform"
    max_position_embeddings: 2048
    vocab_size: 50257
    # Decoder
    num_hidden_layers: 24
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5 # change to 1.0e-12 for single precision training

    # Decoder - Attention
    num_heads: 16 # NOTE: Paper says "24" but was typo. Confirmed with authors
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Decoder - ffn
    filter_size: 8192
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Task-specific
    use_bias_in_output: False
    loss_scaling: "batch_size"
    loss_weight: 0.00048828125 # = 1/max_sequence_length

    # Cerebras parameters
    mixed_precision: True
    precision_opt_level: 1

### Optimization
optimizer:
    optimizer_type: "AdamW"
    weight_decay_rate: 0.1
    max_gradient_norm: 1.0
    learning_rate:
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 2.0e-4
        steps: 1500 # approx 375M tokens at batch size 121 and msl 2048
      - scheduler: "CosineDecay"
        initial_learning_rate: 2.0e-4
        end_learning_rate: 2.0e-5
        decay_steps: 1050000 # approx 260B tokens at batch size 121 and msl 2048
      - scheduler: "Constant"
        learning_rate: 2.0e-5

### Cerebras parameters
runconfig:
    # GPT-3 models trained for 300B tokens
    max_steps: 1200000
    log_steps: 100
    save_checkpoint_steps: 12000
    save_summary_steps: 100
    eval_steps: 50

