# GPT-3 6.7B model
# Adopted from https://github.com/Cerebras/monolith/blob/master/src/models/transformers/tf/gpt2/configs/params_gpt3_lm_6p7b_bs85.yaml

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir:
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/0/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/1/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/2/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/3/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/4/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/5/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/6/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/7/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/8/
      - ./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/9/
    vocab_size: 50257
    max_sequence_length: 2048
    shuffle: True
    shuffle_seed: 12345
    repeat: True
    batch_size: 65
    num_workers: 8

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_msl2048"
    vocab_size: 50257
    max_sequence_length: 2048
    shuffle: False
    repeat: False
    batch_size: 65

model:
    # Embedding
    hidden_size: 4096
    use_position_embedding: True
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 2048
    vocab_size: 50257

    # Encoder
    num_hidden_layers: 32
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5

    # Encoder - Attention
    num_heads: 32
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    fixed_sparse_attention: null

    # Encoder - ffn
    filter_size: 16384
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Task-specific
    # loss_scaling defaults to num_tokens
    use_bias_in_output: False
    loss_scaling: "num_tokens"

    # Cerebras parameters
    mixed_precision: True
    precision_opt_level: 1

    # softmax fp16
    attention_softmax_fp32: False

    # Enable bfloat16 for all.
    use_bfloat16: False

    embedding_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02
        a: -0.04
        b: 0.04

    initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02
        a: -0.04
        b: 0.04

    output_layer_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.0025 # 0.02 / sqrt(2 * num_hidden_layers)

optimizer:
    optimizer_type: "adamw"
    beta1: 0.9
    beta2: 0.95
    max_gradient_norm: 1.0
    correct_bias: True
    loss_scaling_factor: "dynamic"
    eps: 1.0e-8
    weight_decay_rate: 0.01
    learning_rate:
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 6.0e-4
        steps: 1000
      - scheduler: "CosineDecay"
        initial_learning_rate: 6.0e-4
        end_learning_rate: 6.0e-5
        decay_steps: 32750
        steps: 32750
    initial_loss_scale: 2147483648.0
    max_loss_scale: 2147483648.0
    log_summaries: True

runconfig:
  max_steps: 150000
  eval_steps: 1528
  save_summary_steps: 1
  checkpoint_steps: 0
  keep_checkpoint_max: 21
  log_step_count_steps: 1
  log_steps: 1
  save_losses: True
  save_initial_checkpoint: True
  seed: 0
  enable_distributed: False # Change to True on GPU
