################################################
## Base configuration: GPT-NeoX 20B params
## Reference for Gpt-NeoX :: https://github.com/EleutherAI/gpt-neox
################################################
train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: 
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/0/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/1/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/2/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/3/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/4/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/5/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/6/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/7/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/8/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/9/"
    vocab_size: 50257 
    max_sequence_length: 2048
    batch_size: 50
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_msl2048/"
    vocab_size: 50257
    max_sequence_length: 2048
    batch_size: 50
    shuffle: False
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

model:
    # Embedding
    vocab_size: 50257 
    position_embedding_type: "rotary"
    share_embedding_weights: False

    # Decoder Block
    hidden_size: 6144
    num_heads: 64
    num_hidden_layers: 44
    max_position_embeddings: 2048
    attention_type: "scaled_dot_product"

    use_untied_layer_norm: True
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True
    use_ffn_bias: True

    filter_size: 24576
    nonlinearity: "gelu"

    rotary_dim: 24
    layer_norm_epsilon: 1.0e-5
    use_bias_in_output: False
    initializer_range: 0.02

    embedding_initializer:
        name: "variance_scaling"
        scale: 0.4
        mode: "fan_out"
        distribution: "normal"

    initializer:
        name: "variance_scaling"
        scale: 0.4
        distribution: "normal"

    output_layer_initializer:
        name: "variance_scaling"
        scale: 0.0020661157 # 4 / num_hidden_layers ** 2
        distribution: "normal"

    mixed_precision: True
    use_bfloat16: True
    precision_opt_level: 1

optimizer:
    optimizer_type: "adamw"
    beta1: 0.9
    beta2: 0.95
    eps: 1.0e-8
    weight_decay_rate: 0.01
    max_gradient_norm: 1.0
    use_bias_correction: True
    max_loss_scale: 4290774016.0
    learning_rate:
        - steps: 1500
          scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 0.97e-4
        - scheduler: "CosineDecay"
          initial_learning_rate: 0.97e-4
          decay_steps: 148500
          end_learning_rate: 0.97e-5 # end_learning_rate = initial_learning_rate * alpha.
    loss_scaling_factor: 1.0

runconfig:
    max_steps: 150000
    log_steps: 100
    checkpoint_steps: 5000
    seed: 1

