# GPT-J 6B model
# Based on src/models/transformers/tf/gptj/configs/params_gptj_6B.yaml

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: 
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/0/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/1/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/2/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/3/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/4/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/5/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/6/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/7/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/8/"
        - "./language/datasets/pile_original/hdf5_dataset/train_msl2048/9/"
    vocab_size: 50257
    max_sequence_length: 2048
    batch_size: 65 # Ideally we want batch size 512, but this doesn't fit on system yet
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_msl2048/"
    vocab_size: 50257
    max_sequence_length: 2048
    batch_size: 65 # Ideally we want batch size 512, but this doesn't fit on system yet
    shuffle: False
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

model:
    # Embedding
    vocab_size: 50257 
    position_embedding_type: "rotary"
    embedding_dropout_rate: 0.0
    share_embedding_weights: False

    # Decoder Block
    hidden_size: 4096
    num_heads: 16
    num_hidden_layers: 28
    max_position_embeddings: 2048
    attention_type: "scaled_dot_product"

    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False
    use_ffn_bias: True

    filter_size: 16384
    nonlinearity: "gelu"
    attention_dropout_rate: 0.0
    residual_dropout_rate: 0.0

    rotary_dim: 64
    layer_norm_epsilon: 1.0e-5
    use_bias_in_output: True
    initializer_range: 0.02

    loss_scaling: "batch_size"
    loss_weight: 0.00048828125 # = 1/max_sequence_length

    embedding_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.00446068668 # 1 / sqrt(vocab_size)

    initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.015625 # 1 / sqrt(hidden_size)

    output_layer_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.00111607142 # 2 / num_hidden_layers / sqrt(hidden_size)

    mixed_precision: True
    precision_opt_level: 1

optimizer:
    optimizer_type: "adamw"
    eps: 1.0e-6
    weight_decay_rate: 0.1
    max_gradient_norm: 1.0
    use_bias_correction: True
    max_loss_scale: 4290774016.0
    learning_rate:
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 4.3e-5
        steps: 25886
      - scheduler: "CosineDecay"
        initial_learning_rate: 4.3e-5
        end_learning_rate: 4.3e-6
        decay_steps: 2588000
      - scheduler: "Constant"
        learning_rate: 4.3e-6

runconfig:
    max_steps: 3020000
    log_steps: 100
    checkpoint_steps: 10000
    keep_checkpoint_max: 2
    enable_distributed: False

