# Copyright 2022 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# GPT-3 model with same hyperparameters as GPT-NeoX 20B

# Notes:
#  - This configuration uses Cerebras' GPT-2 model implementation as a
#    baseline, but OpenAI's GPT-3 uses their sparse attention implementation.
#  - For efficient training, we also use OpenAI and DeepMind scaling laws to
#    predict the number of tokens to train for. Specifically, we train with
#    OpenAI's predicted tokens for the given model size, and we use the
#    learning rate schedule (linear warmup + cosine decay) recommended by
#    DeepMind Chinchilla paper.

### Input
train_input:
    data_processor: "GptTfRecordsProcessor"
    data_dir:
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/0"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/1"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/2"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/3"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/4"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/5"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/6"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/7"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/8"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_msl2048/9"
    vocab_size: 50257
    max_sequence_length: 2048
    shuffle: True
    repeat: True
    batch_size: 50
    use_multiple_workers: False  # Set to True when using multiple workers on CS-1.
    mixed_precision: True

eval_input:
    data_processor: "GptTfRecordsProcessor"
    data_dir: "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/val_msl2048"
    vocab_size: 50257
    max_sequence_length: 2048
    batch_size: 50
    mixed_precision: True

### Model
model:
    # Embedding
    hidden_size: 6144
    use_position_embedding: True
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 2048

    # Encoder
    num_hidden_layers: 44
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5 # change to 1.0e-12 for single precision training

    # Encoder - Attention
    num_heads: 64
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: True

    # Encoder - ffn
    filter_size: 24576
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Task-specific
    use_bias_in_output: False
    loss_scaling: "batch_size"
    loss_weight: 0.00048828125 # 1/MSL=>1/2048

    # Cerebras parameters
    mixed_precision: True
    boundary_casting: False
    tf_summary: False
    precision_opt_level: 0

### Optimization
optimizer:
    optimizer_type: "adamw"
    beta1: 0.9
    beta2: 0.95
    epsilon: 1.0e-5
    use_bias_correction: True
    weight_decay_rate: 0.05
    max_gradient_norm: 1.0
    # GPT-3 warms-up training over the first 375M tokens
    # Then, the DeepMind approach cosine decays learning rate over the rest
    # of the training steps
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 4.5e-5
          steps: 3000
        - scheduler: "Cosine"
          initial_learning_rate: 4.5e-5
          alpha: 0.1
          decay_steps: 262000
          steps: 262000
    loss_scaling_factor: "dynamic"
    initial_loss_scale: 2147483648.0
    max_loss_scale: 2147483648.0
    log_summaries: True
    ws_summary: True

### Cerebras parameters
runconfig:
    max_steps: 265000
    save_summary_steps: 10
    log_step_count_steps: 10
    save_checkpoints_steps: 5000
    tf_random_seed: 0
    num_wgt_servers: 15

