# Copyright 2022 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# GPT-3 x-large model (1.3B parameters)
# Works with CS-2 in weight streaming mode.
# 2.498e20 training FLOPs
# This exact config was run on 8 CS-2 machines and achieved 1.9989 PILE validation loss
#
# To adapt this config to run on fewer CS-2 machines, you need to enable gradient accumulation doing adding the following yaml changes:
# ```
# train_input:
# 	batch_size: PER_BOX_BATCH_SIZE
# model:
#             loss_scaling: "batch_size"
#             loss_weight: 0.00048828125 # 1/2048
# ```
#
# As well as the following ini flags:
# ```
# ws_opt_disable_grad_accum: false
# ws_opt_force_max_grad_accum_batch: MICRO_BATCH_SIZE
# ```
#
# MICRO_BATCH_SIZE refers to the batch size used in each forward pass on each system.
# PER_BOX_BATCH_SIZE = N_GRADIENT_ACCUMULATION_STEPS * MICRO_BATCH_SIZE
#
# For example if you want to train with GLOBAL_BATCH_SIZE=528 and MICRO_BATCH_SIZE=66
# - 1-box: N_GRADIENT_ACCUMULATION_STEPS=8,  PER_BOX_BATCH_SIZE=528
# - 2-box: N_GRADIENT_ACCUMULATION_STEPS=4,  PER_BOX_BATCH_SIZE=264
# - 4-box: N_GRADIENT_ACCUMULATION_STEPS=2,  PER_BOX_BATCH_SIZE=132
# - 8-box: No gradient accumulation needed.


### Input
train_input:
    data_processor: "GptTfRecordsProcessor"
    add_special_tokens: False
    data_dir: 
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_shuffled_msl2048/0"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_shuffled_msl2048/1"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_shuffled_msl2048/2"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_shuffled_msl2048/3"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_shuffled_msl2048/4"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_shuffled_msl2048/5"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_shuffled_msl2048/6"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_shuffled_msl2048/7"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_shuffled_msl2048/8"
        - "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/train_shuffled_msl2048/9"
    vocab_size: 50257
    max_sequence_length: 2048
    shuffle: True
    shuffle_seed: 256
    repeat: True
    batch_size: 66 # global batch size with 8 CS-2s: 66 x 8 = 528
    use_multiple_workers: False  # Set to True when using multiple workers on CS-1.

eval_input:
    data_processor: "GptTfRecordsProcessor"
    data_dir: "./language/datasets/pile_original/new_tfrecords/gpt2_encoding/val_msl2048"
    add_special_tokens: False
    vocab_size: 50257
    max_sequence_length: 2048
    shuffle: False
    repeat: False
    batch_size: 66

### Model
model:
    # Embedding
    hidden_size: 2048
    use_position_embedding: True
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 2048

    # Encoder
    num_hidden_layers: 24
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5

    # Encoder - Attention
    num_heads: 16
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Encoder - ffn
    filter_size: 8192
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Task-specific
    use_bias_in_output: False
    weight_initialization_seed: 0

    # Cerebras parameters
    mixed_precision: True
    boundary_casting: False
    tf_summary: False
    precision_opt_level: 0

### Optimization
optimizer:
    optimizer_type: "adamw"
    beta1: 0.9
    beta2: 0.95
    epsilon: 1.0e-8
    weight_decay_rate: 0.1
    max_gradient_norm: 1.0
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 2.0e-4
          steps: 346 # approx 375M tokens (global batch size 528 and msl 2048)
        - scheduler: "Cosine"
          initial_learning_rate: 2.0e-4
          alpha: 0.1
          decay_steps: 23988
    loss_scaling_factor: "dynamic" # Change to "tf_dynamic" on GPU
    initial_loss_scale: 65536.0
    max_loss_scale: 2147483648.0
    use_bias_correction: True
    log_summaries: True

### Runtime
runconfig:
    max_steps: 24334 # approx 26B tokens (global batch size 528 and msl 2048)
    eval_steps: 1534 # approx 380M tokens (batch size 121 and msl 2048)
    save_summary_steps: 10
    log_step_count_steps: 10
    save_checkpoints_steps: 5000
    keep_checkpoint_max: 2
    tf_random_seed: 0
    enable_distributed: False

